--8. 한 사원과 같은 부서에서 일하는 사원의 이름 조회
SELECT E.EMP_NAME,E.DEPT_CODE,M.EMP_NAME
FROM EMPLOYEE E
    JOIN EMPLOYEE M ON E.DEPT_CODE=M.DEPT_CODE
WHERE E.EMP_NAME!=M.EMP_NAME
ORDER BY E.EMP_NAME;

--9. 보너스가 없고 직급 코드가 J4이거나 J7인 사원의 이름, 직급 명, 급여 조회(NVL 이용)
SELECT EMP_NAME,JOB_NAME,NVL(BONUS,SALARY)
FROM EMPLOYEE
    JOIN JOB USING (JOB_CODE)
WHERE JOB_CODE IN ('J4','J7');

--10. 보너스 포함한 연봉이 높은 5명의 사번, 이름, 부서 명, 직급, 입사일, 순위 조회
SELECT T.*,ROWNUM
FROM (SELECT EMP_ID,EMP_NAME,DEPT_TITLE,JOB_NAME,HIRE_DATE 
    FROM EMPLOYEE  
    JOIN JOB USING(JOB_CODE)
    JOIN DEPARTMENT ON DEPT_CODE=DEPT_ID
    ORDER BY (SALARY+SALARY*NVL(BONUS,0))*12 DESC) T
WHERE ROWNUM<=5;

--11. 부서 별 급여 합계가 전체 급여 총 합의 20%보다 많은 부서의 부서 명, 부서 별 급여 합계 조회
--11-1 JOIN과 HAVING 사용
SELECT DEPT_TITLE,SUM(SALARY)
FROM DEPARTMENT  
    JOIN EMPLOYEE  ON DEPT_CODE = DEPT_ID   
GROUP BY DEPT_TITLE
HAVING SUM(SALARY)>(SELECT SUM(SALARY)*0.2 FROM EMPLOYEE);

-- 11-2.인라인 뷰 사용
SELECT *
FROM (
SELECT DEPT_TITLE,SUM(SALARY) AS TOTAL
FROM DEPARTMENT  
    JOIN EMPLOYEE  ON DEPT_CODE = DEPT_ID   
GROUP BY DEPT_TITLE
)
WHERE TOTAL >(SELECT SUM(SALARY)*0.2 FROM EMPLOYEE);

-- 11-3. WITH 사용   
WITH TOPN_SAL AS(SELECT DEPT_TITLE,SUM(SALARY) AS TOTAL
FROM DEPARTMENT  
    JOIN EMPLOYEE  ON DEPT_CODE = DEPT_ID   
GROUP BY DEPT_TITLE)
SELECT * FROM TOPN_SAL 
WHERE TOTAL > (SELECT SUM(SALARY)*0.2 FROM EMPLOYEE);

--12. 부서 명과 부서 별 급여 합계 조회
SELECT DEPT_TITLE,SUM(SALARY)
FROM DEPARTMENT
    RIGHT JOIN EMPLOYEE  ON DEPT_CODE = DEPT_ID   
GROUP BY DEPT_TITLE;








    

